enable_platform:
  - moenv_platform

api_platforms:
  - id: moenv_platform
    name: 環境部環境資料開放平臺
    description: 提供環境部相關的開放資料，例如空氣品質、酸雨監測等。
    spec_pathname: config/openapi_specs/環境部環境資料開放平臺_openapi.yaml
    enable: true
    authentication:
      method: api_key
      key_env_var: 環境部環境資料開放平臺_KEY
    system_prompt: |
      你是一個環境部開放資料的專家。
      當使用者詢問環境相關問題時，請利用環境部提供的工具來查詢資料。
      例如：空氣品質、酸雨監測、水質監測等。
    process_tag: environment_data
  - id: 交通部運輸研究運輸技術研究中心
    name: 交通部運輸研究運輸技術研究中心
    description: 提供交通部運輸研究運輸技術研究中心 相關的開放資料。
    spec_pathname: config/openapi_specs/交通部運輸研究運輸技術研究中心_openapi.yaml
    enable: false
    authentication:
      method: api_key
      key_env_var: 交通部運輸研究運輸技術研究中心_KEY
    system_prompt: 你是一個 交通部運輸研究運輸技術研究中心 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 交通部運輸研究運輸技術研究中心
  - id: 金管會金融統計資料v2
    name: 金管會金融統計資料V2
    description: 提供金管會金融統計資料V2 相關的開放資料。
    spec_pathname: config/openapi_specs/金管會金融統計資料v2_openapi.json
    enable: false
    authentication:
      method: api_key
      key_env_var: 金管會金融統計資料V2_KEY
    system_prompt: 你是一個 金管會金融統計資料V2 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 金管會金融統計資料v2
  - id: 客家委員會開放資料平台
    name: 客家委員會開放資料平台
    description: 提供客家委員會開放資料平台 相關的開放資料。
    spec_pathname: config/openapi_specs/客家委員會開放資料平台_openapi.json
    enable: false
    authentication:
      method: api_key
      key_env_var: 客家委員會開放資料平台_KEY
    system_prompt: 你是一個 客家委員會開放資料平台 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 客家委員會開放資料平台
  - id: 政府資料標準平臺
    name: 政府資料標準平臺
    description: 提供政府資料標準平臺 相關的開放資料。
    spec_pathname: config/openapi_specs/政府資料標準平臺_openapi.yaml
    enable: false
    authentication:
      method: api_key
      key_env_var: 政府資料標準平臺_KEY
    system_prompt: 你是一個 政府資料標準平臺 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 政府資料標準平臺
  - id: 財政部財政資訊中心政府資料開放
    name: 財政部財政資訊中心政府資料開放
    description: 提供財政部財政資訊中心政府資料開放 相關的開放資料。
    spec_pathname: config/openapi_specs/財政部財政資訊中心政府資料開放_openapi.json
    enable: false
    authentication:
      method: api_key
      key_env_var: 財政部財政資訊中心政府資料開放_KEY
    system_prompt: 你是一個 財政部財政資訊中心政府資料開放 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 財政部財政資訊中心政府資料開放
  - id: 財政部電子發票整合服務平台
    name: 財政部電子發票整合服務平台
    description: 提供財政部電子發票整合服務平台 相關的開放資料。
    spec_pathname: config/openapi_specs/財政部電子發票整合服務平台_openapi.json
    enable: false
    authentication:
      method: api_key
      key_env_var: 財政部電子發票整合服務平台_KEY
    system_prompt: 你是一個 財政部電子發票整合服務平台 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 財政部電子發票整合服務平台
  - id: 經濟部水利署水利資料開放平台
    name: 經濟部水利署水利資料開放平台
    description: 提供經濟部水利署水利資料開放平台 相關的開放資料。
    spec_pathname: config/openapi_specs/經濟部水利署水利資料開放平台_openapi.json
    enable: false
    authentication:
      method: api_key
      key_env_var: 經濟部水利署水利資料開放平台_KEY
    system_prompt: 你是一個 經濟部水利署水利資料開放平台 的專家。請利用提供的工具來查詢相關資料。
    process_tag: 經濟部水利署水利資料開放平台
  - id: i運動資訊平台
    name: I運動資訊平台
    description: 提供I運動資訊平台 相關的開放資料。
    spec_pathname: config/openapi_specs/i運動資訊平台_openapi.json
    enable: false
    authentication:
      method: api_key
      key_env_var: I運動資訊平台_KEY
    system_prompt: 你是一個 I運動資訊平台 的專家。請利用提供的工具來查詢相關資料。
    process_tag: i運動資訊平台